"""Make System User fields nullable for Page Token Flow

Revision ID: 028aafb369fc
Revises: e04285eebfdf
Create Date: 2026-01-22 17:17:16.808151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028aafb369fc'
down_revision = 'e04285eebfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('current_session_id')

    with op.batch_alter_table('facebook_connections', schema=None) as batch_op:
        batch_op.alter_column('business_manager_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('system_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('facebook_connections_admin_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_facebook_connections_admin_id'), ['admin_id'], unique=True)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_facebook_lead_id'), ['facebook_lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_facebook_lead_id'))

    with op.batch_alter_table('facebook_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facebook_connections_admin_id'))
        batch_op.create_unique_constraint(batch_op.f('facebook_connections_admin_id_key'), ['admin_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('system_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('business_manager_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
