"""Added scalability indexes

Revision ID: 5eb77c1b3672
Revises: 028aafb369fc
Create Date: 2026-01-27 13:13:16.896234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5eb77c1b3672'
down_revision = '028aafb369fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. App Usage Index
    with op.batch_alter_table('app_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_usage_start_time'), ['start_time'], unique=False)

    # 2. Call History Indexes
    with op.batch_alter_table('call_history', schema=None) as batch_op:
        batch_op.create_index('idx_call_history_call_type', ['call_type'], unique=False)
        batch_op.create_index('idx_call_history_phone', ['phone_number'], unique=False)
        batch_op.create_index('idx_call_history_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_history_created_at'), ['created_at'], unique=False)

    # 3. Lead Indexes
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_source'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    with op.batch_alter_table('call_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_history_created_at'))
        batch_op.drop_index('idx_call_history_timestamp')
        batch_op.drop_index('idx_call_history_phone')
        batch_op.drop_index('idx_call_history_call_type')

    with op.batch_alter_table('app_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_usage_start_time'))

    # ### end Alembic commands ###
